/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadScripts".
 */
export type HeadScripts =
  | {
      type: "external" | "inline" | "custom";
      src?: string | null;
      content?: string | null;
      async?: boolean | null;
      defer?: boolean | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RollerSkatingWaiverFormDependent".
 */
export type RollerSkatingWaiverFormDependent =
  | {
      name: string;
      qid?: string | null;
      phone?: string | null;
      birth_date: string;
      age: number;
      medical_conditions?: string | null;
      medications?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkiWaiverFormDependent".
 */
export type SkiWaiverFormDependent =
  | {
      name: string;
      qid?: string | null;
      age: number;
      medical_conditions?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RollerSkatingWaiverContentDetail".
 */
export type RollerSkatingWaiverContentDetail =
  | {
      title?: string | null;
      description?:
        | {
            [k: string]: unknown;
          }[]
        | null;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkiWaiverContentDetail".
 */
export type SkiWaiverContentDetail =
  | {
      title?: string | null;
      description?:
        | {
            [k: string]: unknown;
          }[]
        | null;
      id?: string | null;
    }[]
  | null;

export interface Config {
  collections: {
    "employee-questions": EmployeeQuestion;
    "employee-questions-new": EmployeeQuestionsNew;
    "employee-questions-group": EmployeeQuestionsGroup;
    "employee-questions-padel": EmployeeQuestionsPadel;
    "employee-questions-email-status": EmployeeQuestionsEmailStatus;
    "employee-responses": EmployeeResponse;
    "employee-responses-padel": EmployeeResponsesPadel;
    "employee-whistle-blower": EmployeeWhistleBlower;
    "employee-internal-training": EmployeeInternalTraining;
    "chat-history": ChatHistory;
    "chat-search-files": ChatSearchFile;
    "finance-expenses": FinanceExpense;
    "survey-customer-satisfactions": SurveyCustomerSatisfaction;
    "survey-customer-feedbacks": SurveyCustomerFeedback;
    "survey-customer-feedbacks-padel": SurveyCustomerFeedbacksPadel;
    "employee-benefits": EmployeeBenefit;
    "employee-benefits-category": EmployeeBenefitsCategory;
    "employee-banner": EmployeeBanner;
    "employee-perks-users": EmployeePerksUser;
    "employee-perks-restaurant-pin": EmployeePerksRestaurantPin;
    "employee-perks-redeem-weekly": EmployeePerksRedeemWeekly;
    "ifly-waiver-forms": IflyWaiverForm;
    "laser-oasis-waiver-forms": LaserOasisWaiverForm;
    "roller-skating-waiver-forms": RollerSkatingWaiverForm;
    "employee-whistle-blower-v2": EmployeeWhistleBlowerV2;
    "employee-questions-management": EmployeeQuestionsManagement;
    "employee-questions-management-email-status": EmployeeQuestionsManagementEmailStatus;
    "employee-responses-management": EmployeeResponsesManagement;
    "kpi-plans-item": KpiPlansItem;
    "kpi-plans-status": KpiPlansStatus;
    "kpi-plans-media": KpiPlansMedia;
    "raffle-974": Raffle974;
    "contact-submission": ContactSubmission;
    "contact-submission-rules": ContactSubmissionRule;
    "revenue-overall": RevenueOverall;
    "revenue-overall-monthly": RevenueOverallMonthly;
    "printemps-loyalty-registration": PrintempsLoyaltyRegistration;
    "printemps-loyalty-registration-store": PrintempsLoyaltyRegistrationStore;
    "printemps-loyalty-registration-media": PrintempsLoyaltyRegistrationMedia;
    "dohaoasis-parking-vehicle": DohaoasisParkingVehicle;
    "dohaoasis-parking-media": DohaoasisParkingMedia;
    "dohaoasis-parking-template": DohaoasisParkingTemplate;
    docs: Doc;
    "docs-categories": DocsCategory;
    "docs-media": DocsMedia;
    "feeds-item": FeedsItem;
    "feeds-item-media": FeedsItemMedia;
    "link-shortener": LinkShortener;
    "link-shortener-media": LinkShortenerMedia;
    "menu-pages": MenuPage;
    menu: Menu;
    "menu-items": MenuItem;
    "menu-categories": MenuCategory;
    "menu-allergens": MenuAllergen;
    "menu-media": MenuMedia;
    "menu-tags": MenuTag;
    "ski-waiver-forms": SkiWaiverForm;
    analytics: Analytics;
    users: User;
    "user-roles": UserRole;
    "user-access": UserAccess;
    operators: Operator;
    "operators-new": OperatorsNew;
    department: Department;
    contents: Content;
    media: Media;
    "media-internal": MediaInternal;
    "survey-net-promoter": SurveyNetPromoter;
    variables: Variable;
    "health-check": HealthCheck;
    items: Item;
    restaurants: Restaurant;
    "kpi-plans-department": KpiPlansDepartment;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  globals: {
    "raffle-974-settings": Raffle974Setting;
    "dohaoasis-parking-settings": DohaoasisParkingSetting;
    "reportings-page": ReportingsPage;
    "reportings-revenue-overall": ReportingsRevenueOverall;
    "reportings-revenue-overall-alsadd": ReportingsRevenueOverallAlsadd;
    "reportings-health-check": ReportingsHealthCheck;
    "reportings-health-check-settings": ReportingsHealthCheckSetting;
    "page-content": PageContent;
    "customer-survey-satisfactions-content": CustomerSurveySatisfactionsContent;
    "feeds-dashboard": FeedsDashboard;
    "roller-skating-waiver-contents": RollerSkatingWaiverContent;
    "menu-import": MenuImport;
    "h2a-oasys-settings": H2AOasysSetting;
    "ski-waiver-contents": SkiWaiverContent;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions".
 */
export interface EmployeeQuestion {
  id: number;
  department?: (number | null) | Department;
  default_title?: string | null;
  default_subtitle?: string | null;
  question_group?: (number | null) | EmployeeQuestionsGroup;
  item?:
    | {
        type?: ("text" | "checkbox") | null;
        language?: ("en" | "ar" | "fr") | null;
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "department".
 */
export interface Department {
  id: number;
  name?: string | null;
  department_subs?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions-group".
 */
export interface EmployeeQuestionsGroup {
  id: number;
  name: string;
  title?: {
    en?: string | null;
    ar?: string | null;
    fr?: string | null;
  };
  langs?: ("en" | "ar" | "fr")[] | null;
  show_sub_department?: boolean | null;
  show_additional_comments?: boolean | null;
  departments?: (number | Department)[] | null;
  show_information?: boolean | null;
  information?: {
    en?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    ar?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    fr?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  operator?: (number | null) | Operator;
  role?: (number | null) | UserRole;
  kpi_department?: (number | null) | KpiPlansDepartment;
  restaurant?: (number | null) | Restaurant;
  access?: (number | null) | UserAccess;
  auth_method?: ("default" | "microsoft") | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators".
 */
export interface Operator {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-roles".
 */
export interface UserRole {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpi-plans-department".
 */
export interface KpiPlansDepartment {
  id: number;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: number;
  logo?: number | Media | null;
  featured_image?: number | Media | null;
  name: string;
  slug: string;
  description?: string | null;
  description_rt?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  options?: {
    include_survey_customer?: boolean | null;
    include_employee_perks?: boolean | null;
    order?: number | null;
  };
  scripts?: HeadScripts;
  additional_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-access".
 */
export interface UserAccess {
  id: number;
  name?: string | null;
  access?:
    | {
        name?: string | null;
        hidden?: boolean | null;
        read?: boolean | null;
        create?: boolean | null;
        update?: boolean | null;
        admin?: boolean | null;
        delete?: boolean | null;
        access?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions-new".
 */
export interface EmployeeQuestionsNew {
  id: number;
  order?: number | null;
  department?: (number | null) | Department;
  default_title?: string | null;
  default_subtitle?: string | null;
  group_label?: string | null;
  required?: boolean | null;
  question_group?: (number | null) | EmployeeQuestionsGroup;
  question_type?: ("rating" | "rating_custom" | "select" | "textarea" | "text" | "scale") | null;
  max_scale?: number | null;
  rating_labels?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  select_options?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  item?:
    | {
        type?: ("text" | "checkbox") | null;
        language?: ("en" | "ar" | "fr") | null;
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions-padel".
 */
export interface EmployeeQuestionsPadel {
  id: number;
  department?: (number | null) | Department;
  default_title?: string | null;
  default_subtitle?: string | null;
  question_group?: (number | null) | EmployeeQuestionsGroup;
  item?:
    | {
        type?: ("text" | "checkbox") | null;
        language?: ("en" | "ar" | "fr") | null;
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions-email-status".
 */
export interface EmployeeQuestionsEmailStatus {
  id: number;
  anonymous_id?: string | null;
  email?: string | null;
  status?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-responses".
 */
export interface EmployeeResponse {
  id: number;
  anonymous_id: string;
  department?: string | null;
  department_sub?: string | null;
  employee_comments?: string | null;
  questions?:
    | {
        question: number | EmployeeQuestionsNew;
        question_type?: ("rating" | "rating_custom" | "select" | "textarea" | "text" | "scale") | null;
        response?: ("strongly-disagree" | "disagree" | "i-do-not-know" | "agree" | "strongly-agree") | null;
        response_text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-responses-padel".
 */
export interface EmployeeResponsesPadel {
  id: number;
  anonymous_id: string;
  department?: string | null;
  department_sub?: string | null;
  employee_comments?: string | null;
  questions?:
    | {
        question: number | EmployeeQuestionsPadel;
        response: "strongly-disagree" | "disagree" | "i-do-not-know" | "agree" | "strongly-agree";
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-whistle-blower".
 */
export interface EmployeeWhistleBlower {
  id: number;
  contact_info?: {
    name?: string | null;
    designation?: string | null;
    department?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  subject_info?: {
    name?: string | null;
    designation?: string | null;
    department?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  witness_info?: {
    name?: string | null;
    designation?: string | null;
    department?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  details?: {
    description?: string | null;
    when?: string | null;
    where?: string | null;
    how?: string | null;
    other_parties_involved?: string | null;
    concerned_about_consequences?: string | null;
    reported_to_employer?: string | null;
    conflicted_individuals?: string | null;
    circumvented_controls?: string | null;
    supporting_docs?:
      | {
          media_internal?: number | MediaInternal | null;
          id?: string | null;
        }[]
      | null;
    other_details?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-internal".
 */
export interface MediaInternal {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-internal-training".
 */
export interface EmployeeInternalTraining {
  id: number;
  information: {
    title: string;
    description?: string | null;
    trainer_name?: string | null;
    training_location?: string | null;
  };
  information_date: {
    date_start: string;
    date_end: string;
  };
  participants?:
    | {
        name?: string | null;
        present?: boolean | null;
        clock_in?: string | null;
        clock_out?: string | null;
        remarks?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-history".
 */
export interface ChatHistory {
  id: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-search-files".
 */
export interface ChatSearchFile {
  id: number;
  name: string;
  media: number | Media;
  parsed_text?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-expenses".
 */
export interface FinanceExpense {
  id: number;
  date: string;
  expenses: {
    payout: number;
    water: number;
    kahramaa: number;
    housing_allowance: number;
    transport_allowance: number;
    other_allowance: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-customer-satisfactions".
 */
export interface SurveyCustomerSatisfaction {
  id: number;
  store_ambience_cleanliness_rating?: string | null;
  store_ambience_visual_presentation_rating?: string | null;
  is_product_availability_variety?: string | null;
  product_availability_variety_rating?: string | null;
  rating_customer_service?: ("very-dissatisfied" | "dissatisfied" | "neutral" | "satisfied" | "very-satisfied") | null;
  is_customer_service_helpful?: string | null;
  checkout_payment_process?: string | null;
  loyalty_program?: string | null;
  rating_loyalty_program_satis?:
    | ("very-dissatisfied" | "dissatisfied" | "neutral" | "satisfied" | "very-satisfied")
    | null;
  communication_promotions?: string | null;
  rating_overall_experience?:
    | ("very-dissatisfied" | "dissatisfied" | "neutral" | "satisfied" | "very-satisfied")
    | null;
  area_for_improvement?: string | null;
  name?: string | null;
  telephone_number?: string | null;
  telephone_number_country?: string | null;
  birth_date?: string | null;
  email_address?: string | null;
  marketing_consent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-customer-feedbacks".
 */
export interface SurveyCustomerFeedback {
  id: number;
  visit_date?: string | null;
  receipt_id?: string | null;
  visited_restaurant?: string | null;
  meal_period?: string | null;
  visit_frequency?: ("daily" | "weekly" | "monthly" | "first-time") | null;
  rating_greeting?: ("poor" | "average" | "good" | "very-good" | "excellent") | null;
  rating_service?: ("poor" | "average" | "good" | "very-good" | "excellent") | null;
  rating_beverage?: ("poor" | "average" | "good" | "very-good" | "excellent") | null;
  rating_food?: ("poor" | "average" | "good" | "very-good" | "excellent") | null;
  rating_value_for_money?: ("poor" | "average" | "good" | "very-good" | "excellent") | null;
  rating_cleanliness?: ("poor" | "average" | "good" | "very-good" | "excellent") | null;
  discovery_method?: string | null;
  will_visit_again?: string | null;
  manager_visit?: string | null;
  favorite_restaurant?: string | null;
  additional_comments?: string | null;
  name?: string | null;
  telephone_number?: string | null;
  telephone_number_country?: string | null;
  birth_date?: string | null;
  email_address?: string | null;
  marketing_consent?: boolean | null;
  discovery_text?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-customer-feedbacks-padel".
 */
export interface SurveyCustomerFeedbacksPadel {
  id: number;
  visit_frequency?: ("daily" | "weekly" | "monthly" | "often") | null;
  why_choose_us?: ("facilities" | "location" | "pricing" | "loyalty_program" | "all_above") | null;
  discovery_method?: ("social_media" | "friends" | "others") | null;
  discovery_method_others?: string | null;
  satifaction_booking_process?: string | null;
  satifaction_booking_process_time_slots?: string | null;
  court_fees_reasonable?: ("yes" | "no") | null;
  recommend_to_others?: ("yes" | "no") | null;
  recommend_to_others_rating?: string | null;
  additional_amenities_wish?: string | null;
  satifaction_overall_quality?: string | null;
  satifaction_customer_service?: string | null;
  share_experience?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-benefits".
 */
export interface EmployeeBenefit {
  id: number;
  name: string;
  general_info: {
    category: (number | EmployeeBenefitsCategory)[];
    media?: (number | null) | Media;
  };
  contact_info?: {
    phone?: string | null;
    email?: string | null;
    point_of_contact?: string | null;
    address?: string | null;
  };
  expiry_date?: string | null;
  external_link?: string | null;
  benefits?:
    | {
        title?: string | null;
        description?: string | null;
        printemps?: string | null;
        dohaoasis?: string | null;
        banyantree?: string | null;
        id?: string | null;
      }[]
    | null;
  attachments?:
    | {
        media: number | Media;
        id?: string | null;
      }[]
    | null;
  terms_and_condition?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-benefits-category".
 */
export interface EmployeeBenefitsCategory {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-banner".
 */
export interface EmployeeBanner {
  id: number;
  name: string;
  media: number | Media;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-perks-users".
 */
export interface EmployeePerksUser {
  id: number;
  user_code?: string | null;
  disabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-perks-restaurant-pin".
 */
export interface EmployeePerksRestaurantPin {
  id: number;
  pin_code: string;
  restaurant: number | Restaurant;
  restaurant_name?: string | null;
  thumbnail?: number | Media | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-perks-redeem-weekly".
 */
export interface EmployeePerksRedeemWeekly {
  id: number;
  user: number | EmployeePerksUser;
  restaurant: number | EmployeePerksRestaurantPin;
  weekKey: string;
  redeemedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ifly-waiver-forms".
 */
export interface IflyWaiverForm {
  id: number;
  date?: string | null;
  name: string;
  qid: string;
  phone: string;
  dependents?:
    | {
        name: string;
        qid?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  signature_svg: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "laser-oasis-waiver-forms".
 */
export interface LaserOasisWaiverForm {
  id: number;
  date?: string | null;
  name: string;
  qid: string;
  phone: string;
  dependents?:
    | {
        name: string;
        qid?: string | null;
        phone?: string | null;
        id?: string | null;
      }[]
    | null;
  signature_svg: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roller-skating-waiver-forms".
 */
export interface RollerSkatingWaiverForm {
  id: number;
  date?: string | null;
  name: string;
  qid: string;
  phone: string;
  birth_date: string;
  age: number;
  emergency_contact_name: string;
  emergency_contact_phone: string;
  packages?: ("package-1" | "package-2" | "package-3") | null;
  consent_media_appearance?: ("yes" | "no") | null;
  dependents?: RollerSkatingWaiverFormDependent;
  signature_svg: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-whistle-blower-v2".
 */
export interface EmployeeWhistleBlowerV2 {
  id: number;
  contact_info?: {
    name?: string | null;
    designation?: string | null;
    department?: (number | null) | Department;
    department_text?: string | null;
    operator?: (number | null) | OperatorsNew;
    phone?: string | null;
    email?: string | null;
  };
  subject_info?: {
    name?: string | null;
    designation?: string | null;
    department?: (number | null) | Department;
    operator?: (number | null) | OperatorsNew;
    phone?: string | null;
    email?: string | null;
  };
  details?: {
    incident_or_concern?: string | null;
  };
  supporting_docs?:
    | {
        media_internal?: number | MediaInternal | null;
        id?: string | null;
      }[]
    | null;
  acknowledgement?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators-new".
 */
export interface OperatorsNew {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions-management".
 */
export interface EmployeeQuestionsManagement {
  id: number;
  department?: (number | null) | Department;
  type?: string | null;
  default_title?: string | null;
  default_subtitle?: string | null;
  item?:
    | {
        type?: ("text" | "checkbox") | null;
        language?: ("en" | "ar" | "fr") | null;
        title?: string | null;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-questions-management-email-status".
 */
export interface EmployeeQuestionsManagementEmailStatus {
  id: number;
  anonymous_id?: string | null;
  email?: string | null;
  status?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-responses-management".
 */
export interface EmployeeResponsesManagement {
  id: number;
  anonymous_id: string;
  department?: string | null;
  department_sub?: string | null;
  employee_comments?: string | null;
  questions?:
    | {
        question: number | EmployeeQuestionsManagement;
        response: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpi-plans-item".
 */
export interface KpiPlansItem {
  id: number;
  name: string;
  description: string;
  department?: (number | null) | KpiPlansDepartment;
  status?: (number | null) | KpiPlansStatus;
  start_date: string;
  end_date: string;
  progress?: number | null;
  weight?: number | null;
  attachments?:
    | {
        document?: number | KpiPlansMedia | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  remarks?: string | null;
  approval_status?: ("pending" | "rejected" | "approved") | null;
  approval_comments?: string | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpi-plans-status".
 */
export interface KpiPlansStatus {
  id: number;
  name: string;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpi-plans-media".
 */
export interface KpiPlansMedia {
  id: number;
  alt?: string | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raffle-974".
 */
export interface Raffle974 {
  id: number;
  full_name: string;
  email: string;
  nationality: string;
  country_of_residence: string;
  accepted_tnc: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submission".
 */
export interface ContactSubmission {
  id: number;
  email?: string | null;
  additional_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source?: string | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submission-rules".
 */
export interface ContactSubmissionRule {
  id: number;
  name: string;
  source_trigger: string;
  active?: boolean | null;
  email_config?: {
    to_emails?:
      | {
          email: string;
          id?: string | null;
        }[]
      | null;
    cc_emails?:
      | {
          email?: string | null;
          id?: string | null;
        }[]
      | null;
    subject_template?: string | null;
    email_template?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revenue-overall".
 */
export interface RevenueOverall {
  id: number;
  date?: string | null;
  date_text?: string | null;
  everfashion: {
    vendome?: number | null;
    villagio?: number | null;
    printemps?: number | null;
  };
  printemps: {
    retail?: number | null;
    fnb?: number | null;
  };
  lacigale_musherib: {
    rooms?: number | null;
    residences?: number | null;
    revenue?: number | null;
  };
  quest: {
    revenue?: number | null;
  };
  novo: {
    revenue?: number | null;
  };
  padel: {
    revenue?: number | null;
  };
  lacigale_alsadd: {
    rooms?: number | null;
    residences?: number | null;
    revenue?: number | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "revenue-overall-monthly".
 */
export interface RevenueOverallMonthly {
  id: number;
  date?: string | null;
  date_text?: string | null;
  everfashion: {
    total?: number | null;
    gdp?: number | null;
  };
  printemps: {
    total?: number | null;
    gdp?: number | null;
  };
  lacigale_musherib: {
    total?: number | null;
    gdp?: number | null;
  };
  quest: {
    total?: number | null;
    gdp?: number | null;
  };
  novo: {
    total?: number | null;
    gdp?: number | null;
  };
  padel: {
    total?: number | null;
    gdp?: number | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printemps-loyalty-registration".
 */
export interface PrintempsLoyaltyRegistration {
  id: number;
  visit_date: string;
  store: number | PrintempsLoyaltyRegistrationStore;
  first_name: string;
  last_name: string;
  phone: string;
  email: string;
  birth_date: string;
  gender: "male" | "female";
  nationality: string;
  receipt?: number | PrintempsLoyaltyRegistrationMedia | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printemps-loyalty-registration-store".
 */
export interface PrintempsLoyaltyRegistrationStore {
  id: number;
  logo?: number | Media | null;
  featured_image?: number | Media | null;
  name: string;
  slug: string;
  description?: string | null;
  description_rt?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  scripts?: HeadScripts;
  additional_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printemps-loyalty-registration-media".
 */
export interface PrintempsLoyaltyRegistrationMedia {
  id: number;
  alt?: string | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dohaoasis-parking-vehicle".
 */
export interface DohaoasisParkingVehicle {
  template: number | DohaoasisParkingTemplate;
  id: string;
  serial_no?: string | null;
  qr?: number | DohaoasisParkingMedia | null;
  plate_no?: string | null;
  zone?: string | null;
  parking_no?: string | null;
  registration_id?: string | null;
  registration_expiry?: string | null;
  remarks?: string | null;
  vehicle?: {
    color?: string | null;
    make?: string | null;
    model?: string | null;
    year?: number | null;
  };
  owner?: {
    type?: ("employee" | "external") | null;
    company?: string | null;
    name?: string | null;
    employee_no?: string | null;
    email?: string | null;
    phone?: string | null;
    department?: (number | null) | Department;
    designation?: string | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dohaoasis-parking-template".
 */
export interface DohaoasisParkingTemplate {
  id: number;
  name?: string | null;
  template: number | DohaoasisParkingMedia;
  serial_options?: {
    prefix?: string | null;
    color?: string | null;
    size?: number | null;
    x?: number | null;
    y?: number | null;
    next_serial_no?: number | null;
  };
  qrcode_options?: {
    color?: string | null;
    size?: number | null;
    x?: number | null;
    y?: number | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dohaoasis-parking-media".
 */
export interface DohaoasisParkingMedia {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  title: string;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  slug: string;
  category?: (number | null) | DocsCategory;
  type?: ("pdf" | "image" | "video") | null;
  file?: number | DocsMedia | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-categories".
 */
export interface DocsCategory {
  id: number;
  title: string;
  slug: string;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-media".
 */
export interface DocsMedia {
  id: number;
  alt?: string | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feeds-item".
 */
export interface FeedsItem {
  id: number;
  media?: number | FeedsItemMedia | null;
  title?: string | null;
  description?: string | null;
  department?: (number | null) | Department;
  status?: ("pending" | "approved" | "rejected" | "acknowledged") | null;
  admin_notes?: string | null;
  attachments?:
    | {
        file?: number | FeedsItemMedia | null;
        id?: string | null;
      }[]
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feeds-item-media".
 */
export interface FeedsItemMedia {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link-shortener".
 */
export interface LinkShortener {
  id: number;
  slug: string;
  link: string;
  description?: string | null;
  qr_png?: number | LinkShortenerMedia | null;
  qr_svg?: number | LinkShortenerMedia | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link-shortener-media".
 */
export interface LinkShortenerMedia {
  id: number;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-pages".
 */
export interface MenuPage {
  id: number;
  info: {
    restaurant?: (number | null) | Restaurant;
    title?: string | null;
    slug_override?: boolean | null;
    slug: string;
  };
  c: {
    font_primary?: number | MenuMedia | null;
    font_secondary?: number | MenuMedia | null;
    primary?: string | null;
    primary_contrast?: string | null;
    bg?: string | null;
    bg_card?: string | null;
    text?: string | null;
    neutral?: string | null;
    menus?: (number | Menu)[] | null;
    blk: BlockSection[];
  };
  adv: {
    className?: string | null;
    css?: string | null;
    js?: string | null;
  };
  seo: {
    title?: string | null;
    description?: string | null;
    image?: number | MenuMedia | null;
  };
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-media".
 */
export interface MenuMedia {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  restaurant?: (number | null) | Restaurant;
  image?: number | MenuMedia | null;
  category_title?: string | null;
  restaurant_title?: string | null;
  slug: string;
  slug_override?: boolean | null;
  category: number | MenuCategory;
  description?: string | null;
  menu_items?:
    | {
        item: number | MenuItem;
        id?: string | null;
      }[]
    | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  title?: string | null;
  slug: string;
  slug_override?: boolean | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  restaurant?: (number | null) | Restaurant;
  image?: number | MenuMedia | null;
  title: string;
  slug: string;
  slug_override?: boolean | null;
  description?: string | null;
  price: number;
  availability_period?: ("breakfast" | "lunch" | "dinner" | "all_day")[] | null;
  allergen?: (number | MenuAllergen)[] | null;
  tags?: (number | MenuTag)[] | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-allergens".
 */
export interface MenuAllergen {
  id: number;
  title: string;
  slug: string;
  slug_override?: boolean | null;
  description?: string | null;
  image?: number | MenuMedia | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-tags".
 */
export interface MenuTag {
  id: number;
  title: string;
  slug: string;
  slug_override?: boolean | null;
  description?: string | null;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockSection".
 */
export interface BlockSection {
  c: {
    blks?:
      | (BlockCarousel | BlockImages | BlockEmbed | BlockText | BlockButtons | BlockHeader | BlockFilter | BlockItems)[]
      | null;
  };
  settings: {
    className?: string | null;
    css?: string | null;
    js?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "section";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCarousel".
 */
export interface BlockCarousel {
  c: {
    slides?:
      | {
          image?: number | MenuMedia | null;
          id?: string | null;
        }[]
      | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "carousel";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockImages".
 */
export interface BlockImages {
  c: {
    image?: number | MenuMedia | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "images";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockEmbed".
 */
export interface BlockEmbed {
  c: {
    html?: string | null;
  };
  settings: {
    css?: string | null;
    js?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "embed";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockText".
 */
export interface BlockText {
  c: {
    label?: string | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "text";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockButtons".
 */
export interface BlockButtons {
  c: {
    label?: string | null;
    link?: string | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "buttons";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHeader".
 */
export interface BlockHeader {
  c: {
    label?: string | null;
    logo?: number | MenuMedia | null;
    show_language?: boolean | null;
    show_notification?: boolean | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "header";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFilter".
 */
export interface BlockFilter {
  c: {
    showSearch?: boolean | null;
    showAllergenFilters?: boolean | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "filter";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockItems".
 */
export interface BlockItems {
  c: {
    title?: string | null;
    description?: string | null;
  };
  settings: {
    css?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: "items";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ski-waiver-forms".
 */
export interface SkiWaiverForm {
  id: number;
  date?: string | null;
  name: string;
  qid: string;
  phone: string;
  age: number;
  emergency_contact_name: string;
  emergency_contact_phone: string;
  dependents?: SkiWaiverFormDependent;
  signature_svg: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: number;
  eventType:
    | "page_view"
    | "click"
    | "form_submission"
    | "modal_open"
    | "modal_close"
    | "error"
    | "search"
    | "options"
    | "other"
    | "video_started"
    | "video_ended";
  path: string;
  elementId?: string | null;
  referrer?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  additionalData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contents".
 */
export interface Content {
  id: number;
  header?:
    | {
        content?: string | null;
        language?: ("en" | "ar" | "fr") | null;
        id?: string | null;
      }[]
    | null;
  info?:
    | {
        content?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        language?: ("en" | "ar" | "fr") | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-net-promoter".
 */
export interface SurveyNetPromoter {
  id: number;
  visit_date?: string | null;
  receipt_id?: string | null;
  employee_id?: string | null;
  customer_feedback?: ("detractor" | "neutral" | "promoter") | null;
  customer_feedback_number?: number | null;
  customer_comments?: string | null;
  survey_customer_feedbacks_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variables".
 */
export interface Variable {
  id: number;
  name: string;
  description?: string | null;
  value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-check".
 */
export interface HealthCheck {
  id: number;
  name?: string | null;
  url: string;
  skip_ssl_check?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "items".
 */
export interface Item {
  id: number;
  name: string;
  description?: string | null;
  items?:
    | {
        values?:
          | {
              key: string;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  owners?: (number | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: "employee-perks-users";
        value: number | EmployeePerksUser;
      }
    | {
        relationTo: "users";
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raffle-974-settings".
 */
export interface Raffle974Setting {
  id: number;
  Content: {
    content?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  Title: {
    title?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dohaoasis-parking-settings".
 */
export interface DohaoasisParkingSetting {
  id: number;
  qr_code_color: {
    light: string;
    dark: string;
  };
  show_plate_no?: boolean | null;
  next_serial_number?: number | null;
  logo?: number | DohaoasisParkingMedia | null;
  font?: number | DohaoasisParkingMedia | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reportings-page".
 */
export interface ReportingsPage {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reportings-revenue-overall".
 */
export interface ReportingsRevenueOverall {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reportings-revenue-overall-alsadd".
 */
export interface ReportingsRevenueOverallAlsadd {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reportings-health-check".
 */
export interface ReportingsHealthCheck {
  id: number;
  recipients: {
    email: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reportings-health-check-settings".
 */
export interface ReportingsHealthCheckSetting {
  id: number;
  recipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  dohaoasis: {
    logo_primary?: number | Media | null;
    logo_secondary?: number | Media | null;
    favicon?: number | Media | null;
    additional_data?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  dohaquest: {
    logo_primary?: number | Media | null;
    logo_secondary?: number | Media | null;
    favicon?: number | Media | null;
    additional_data?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  printemps: {
    logo_primary?: number | Media | null;
    logo_secondary?: number | Media | null;
    favicon?: number | Media | null;
    additional_data?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-survey-satisfactions-content".
 */
export interface CustomerSurveySatisfactionsContent {
  id: number;
  header_image?: number | Media | null;
  header_logo?: number | Media | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feeds-dashboard".
 */
export interface FeedsDashboard {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roller-skating-waiver-contents".
 */
export interface RollerSkatingWaiverContent {
  id: number;
  primary_logo?: number | Media | null;
  secondary_logo?: number | Media | null;
  title?: string | null;
  details?: RollerSkatingWaiverContentDetail;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-import".
 */
export interface MenuImport {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "h2a-oasys-settings".
 */
export interface H2AOasysSetting {
  id: number;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  base_url?: string | null;
  client_id?: string | null;
  secret?: string | null;
  last_token_response?: string | null;
  last_token_response_updated_by?: string | null;
  divisions?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  employee_info_last_updated_at?: string | null;
  employee_info?: string | null;
  employee_doj_last_updated_at?: string | null;
  employee_doj?: string | null;
  employee_budget_last_updated_at?: string | null;
  employee_budget?: string | null;
  employee_probation_last_updated_at?: string | null;
  employee_probation?: string | null;
  employee_on_leave_last_updated_at?: string | null;
  employee_on_leave?: string | null;
  employee_leave_history_last_updated_at?: string | null;
  employee_on_leave_history?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ski-waiver-contents".
 */
export interface SkiWaiverContent {
  id: number;
  primary_logo?: number | Media | null;
  secondary_logo?: number | Media | null;
  title?: string | null;
  details?: SkiWaiverContentDetail;
  created_by?: (number | null) | User;
  updated_by?: (number | null) | User;
  _status?: ("draft" | "published") | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
