
@urlBase = {{$dotenv BASE_URL}}
@payloadItem = kpi-plans-department
@apiKey = {{$dotenv API_TOKEN}}
@url = {{urlBase}}/{{payloadItem}}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Information Technology"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Marketing"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Buying"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Engineering"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Executive Office"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Food and beverage"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Finance"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Purchasing"
}