
@urlBase = {{$dotenv BASE_URL}}
@payloadItem = kpi-plans-status
@apiKey = {{$dotenv API_TOKEN}}
@url = {{urlBase}}/{{payloadItem}}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Completed"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "In Progress"
}

### POST
POST {{url}}
Content-Type: application/json
Authorization: users API-Key {{apiKey}}

{
    "name": "Planned"
}