import type { Payload, RequiredDataFromCollectionSlug } from 'payload'
import { Operator, WorkflowV2 } from '@/payload-types'
import { createForm } from './helpers/create-form'
import { thanksConfirmation } from './helpers/form-confirmations'

const incidentFormSlug = 'printemps-incident-forms'

// Dedicated crm-incident-workflow workflow-v2 blueprint (Security Manager
// review, then the store department the submitter selected below).
// Source: .temp/PRT-SFM-INCT-01.xlsx (Tracker sheet headers row 7, dropdown
// options from the Properties sheet) — see .temp/2026-07-26-incident-report-fields.md
export const seedPrintempsIncidentForm = async (
  payload: Payload,
  operator: Operator,
  incidentWorkflow: WorkflowV2 | undefined,
): Promise<void> => {
  const incidentFormData = {
    title: 'Printemps Incident Form',
    slug: incidentFormSlug,
    operator: operator.id,
    operator_slug: `${operator.slug}-${incidentFormSlug}`,
    // Same reasoning as store-floor-customer-complaints: without this, workflow
    // initiation for an authenticated submitter whose own operator doesn't match
    // can fail with "No operator resolved to create a workflow instance."
    override_user_operator: true,
    theme: 'printemps',
    available_languages: ['EN'],
    requires_auth: true,
    required_access: 'form-printemps-incident-forms',
    enable_workflow: true,
    use_workflow_v2: !!incidentWorkflow,
    workflow_v2: incidentWorkflow ? incidentWorkflow.id : undefined,
    workflow_slug: incidentWorkflow ? 'crm-incident-workflow' : undefined,
    enable_form_status: false,
    enable_public_submission_link: false,
    isActive: true,
    emails: [],
    confirmationType: 'message',
    confirmationMessage: thanksConfirmation,
    fields: [
      {
        blockType: 'multi-step',
        steps: [
          {
            label: 'Incident Classification',
            fields: [
              {
                blockType: 'select-store-departments',
                name: 'store_department',
                label: 'Store Department',
                variant: 'label-on-top',
                required: true,
                add_all: true,
                selected_items: [],
              },
              {
                blockType: 'select',
                name: 'incident_type',
                label: 'Incident Type',
                variant: 'label-on-top',
                required: true,
                options: [
                  { label: 'HSE', value: 'hse' },
                  { label: 'Security', value: 'security' },
                  { label: 'Non-HSE', value: 'non_hse' },
                  { label: 'Blank', value: 'blank' },
                  { label: 'Medical', value: 'medical' },
                  { label: 'Staff Behavior', value: 'staff_behavior' },
                ],
              },
              {
                blockType: 'select',
                name: 'incident_group',
                label: 'Incident Group',
                variant: 'label-on-top',
                required: true,
                options: [
                  { label: 'Near Miss', value: 'near_miss' },
                  { label: 'Accident', value: 'accident' },
                  { label: 'Health', value: 'health' },
                  { label: 'Fire', value: 'fire' },
                  { label: 'Other', value: 'other' },
                  { label: 'Staff Behavior', value: 'staff_behavior' },
                ],
              },
              {
                blockType: 'select',
                name: 'incident_nature',
                label: 'Incident Nature',
                variant: 'label-on-top',
                required: true,
                options: [
                  { label: 'Impact', value: 'impact' },
                  { label: 'Collision', value: 'collision' },
                  { label: 'Slip', value: 'slip' },
                  { label: 'Ill Health', value: 'ill_health' },
                  { label: 'Slip, trip or fall', value: 'slip_trip_or_fall' },
                  { label: 'Unauthorized Access', value: 'unauthorized_access' },
                  { label: 'Cut, laceration', value: 'cut_laceration' },
                  { label: 'Entrapment', value: 'entrapment' },
                  { label: 'Smoke', value: 'smoke' },
                  { label: 'Missing person', value: 'missing_person' },
                  { label: 'Property damage', value: 'property_damage' },
                  { label: 'Shock or panic', value: 'shock_or_panic' },
                  { label: 'Unauthorized Work', value: 'unauthorized_work' },
                  { label: 'Unruly behaviour', value: 'unruly_behaviour' },
                  { label: 'Violent Behaviour', value: 'violent_behaviour' },
                  { label: 'Major injury', value: 'major_injury' },
                  {
                    label: 'Seizure, Heart Attack, Stroke',
                    value: 'seizure_heart_attack_stroke',
                  },
                  { label: 'Burn', value: 'burn' },
                  { label: 'Scam', value: 'scam' },
                  { label: 'Theft', value: 'theft' },
                  { label: 'Cheat', value: 'cheat' },
                  { label: 'Employee Intention', value: 'employee_intention' },
                  { label: 'Price Change', value: 'price_change' },
                  { label: 'FIRE', value: 'fire_caps' },
                  { label: 'Food Poisoning', value: 'food_poisoning' },
                  { label: 'Food Complaint', value: 'food_complaint' },
                ],
              },
              {
                blockType: 'select',
                name: 'persons_involved',
                label: 'Persons Involved',
                variant: 'label-on-top',
                required: true,
                options: [
                  { label: 'Employee', value: 'employee' },
                  { label: 'Visitor', value: 'visitor' },
                  { label: 'Contractor', value: 'contractor' },
                  { label: 'Tenant', value: 'tenant' },
                  { label: 'Customer', value: 'customer' },
                  { label: 'Others', value: 'others' },
                  { label: 'NONE', value: 'none' },
                  { label: 'Client', value: 'client' },
                ],
              },
              {
                blockType: 'select',
                name: 'injured_person_staff_group',
                label: 'Injured Person Staff Group',
                variant: 'label-on-top',
                required: true,
                options: [
                  { label: 'DO', value: 'do' },
                  { label: 'Printemps', value: 'printemps' },
                  { label: 'Quest', value: 'quest' },
                  { label: 'Kien', value: 'kien' },
                  { label: 'Supplier', value: 'supplier' },
                  { label: 'NONE', value: 'none' },
                  { label: 'Client', value: 'client' },
                ],
              },
              {
                blockType: 'select',
                name: 'incident_location',
                label: 'Incident Location',
                variant: 'label-on-top',
                required: true,
                options: [
                  { label: 'Store - Beauty', value: 'store_beauty' },
                  { label: 'Loading Bay', value: 'loading_bay' },
                  { label: 'Office - M2', value: 'office_m2' },
                  { label: 'Office - M1', value: 'office_m1' },
                  { label: 'Office - TF', value: 'office_tf' },
                  { label: 'Store - Toys', value: 'store_toys' },
                  { label: 'Novo Cinema', value: 'novo_cinema' },
                  { label: 'Parking Area', value: 'parking_area' },
                  { label: 'Basement', value: 'basement' },
                  { label: 'Spa', value: 'spa' },
                  { label: 'Store - Luxury Jewellery', value: 'store_luxury_jewellery' },
                  { label: "Store - Women's wear", value: 'store_womens_wear' },
                  { label: 'Store - Kids section', value: 'store_kids_section' },
                  { label: 'Russo', value: 'russo' },
                  { label: 'Mosavali', value: 'mosavali' },
                  { label: 'Daryema', value: 'daryema' },
                  { label: 'Duck Doughnuts', value: 'duck_doughnuts' },
                  { label: 'Salon De The', value: 'salon_de_the' },
                  { label: 'Wild & The Moon', value: 'wild_and_the_moon' },
                  { label: 'Cova', value: 'cova' },
                  { label: 'Store - Home & Tech', value: 'store_home_and_tech' },
                  { label: 'Crazy Pizza', value: 'crazy_pizza' },
                  { label: 'Pierre Marcolino', value: 'pierre_marcolino' },
                  { label: 'M1 Kids', value: 'm1_kids' },
                  { label: 'M1 Footwear', value: 'm1_footwear' },
                  { label: "M1 Women's", value: 'm1_womens' },
                  { label: 'M2 Beauty', value: 'm2_beauty' },
                  { label: 'M2 Luxury', value: 'm2_luxury' },
                  { label: 'R4', value: 'r4' },
                  { label: 'M2 Home', value: 'm2_home' },
                  { label: 'M2 Men', value: 'm2_men' },
                  { label: 'M2 Acc', value: 'm2_acc' },
                  { label: 'GF', value: 'gf' },
                  { label: 'VIP', value: 'vip' },
                  { label: 'GF "Doha Oasis"', value: 'gf_doha_oasis' },
                  { label: 'Other', value: 'other' },
                ],
              },
              {
                blockType: 'conditional',
                name: 'incident_location_conditional',
                condition_field: 'incident_location',
                operator: 'equal',
                value: 'other',
                fields: [
                  {
                    blockType: 'text',
                    name: 'incident_location_other',
                    label: 'Please indicate location',
                    required: true,
                  },
                ],
              },
              {
                blockType: 'date',
                name: 'incident_date',
                label: 'Incident Date',
                variant: 'label-on-top',
                required: true,
              },
              {
                blockType: 'time',
                name: 'incident_time',
                label: 'Incident Time',
                variant: 'label-on-top',
                required: true,
              },
            ],
          },
          {
            label: 'Incident Details',
            fields: [
              {
                blockType: 'textarea',
                name: 'brief_description',
                label: 'Brief Description',
                variant: 'label-on-top',
                required: true,
              },
              {
                blockType: 'list',
                name: 'photographic_evidence',
                label: 'Photographic Evidence',
                variant: 'label-on-top',
                fields: [
                  {
                    blockType: 'file',
                    name: 'file',
                    label: 'File',
                    required: false,
                  },
                ],
              },
              {
                blockType: 'textarea',
                name: 'immediate_corrective_action',
                label: 'Immediate Corrective Action',
                variant: 'label-on-top',
                required: true,
              },
              {
                blockType: 'textarea',
                name: 'root_cause',
                label: 'Root Cause',
                variant: 'label-on-top',
                required: false,
              },
              {
                blockType: 'number',
                name: 'loss_time_days',
                label: 'Loss Time in Days',
                variant: 'label-on-top',
                required: false,
              },
              {
                blockType: 'textarea',
                name: 'future_actions',
                label: 'Future Actions Required to Prevent Recurrence',
                variant: 'label-on-top',
                required: false,
              },
              {
                blockType: 'select',
                name: 'risk_assessment_review_required',
                label: 'Risk Assessment Review Required?',
                variant: 'label-on-top',
                required: false,
                options: [
                  { label: 'Yes', value: 'yes' },
                  { label: 'No', value: 'no' },
                ],
              },
            ],
          },
          {
            label: 'Reporting Info',
            fields: [
              {
                blockType: 'text',
                name: 'logged_by',
                label: 'Logged By',
                variant: 'label-on-top',
                required: true,
              },
              {
                blockType: 'text',
                name: 'mode_of_reporting',
                label: 'Mode of Reporting',
                variant: 'label-on-top',
                required: false,
              },
              {
                blockType: 'date',
                name: 'date_incident_logged',
                label: 'Date Incident Logged',
                variant: 'label-on-top',
                required: true,
              },
              {
                blockType: 'text',
                name: 'action_taken_by',
                label: 'Action Taken by',
                variant: 'label-on-top',
                required: false,
              },
              {
                blockType: 'date',
                name: 'date_closed',
                label: 'Date Closed',
                variant: 'label-on-top',
                required: false,
              },
              {
                blockType: 'list',
                name: 'supporting_docs',
                label: 'Supporting Docs / Images',
                variant: 'label-on-top',
                fields: [
                  {
                    blockType: 'file',
                    name: 'file',
                    label: 'File',
                    required: false,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  } as RequiredDataFromCollectionSlug<'forms'>

  await createForm(payload, incidentFormData)
}
