import { Form } from '@/payload-types'

/**
 * Vendor Registration Form Fields
 *
 * Fields are organized into groups matching the dot-notation schema:
 *   group.fieldName → nested paths (e.g. companyDetails.name)
 */
export const vendorRegistrationFields: Form['fields'] = [
  {
    id: '69d24e49f0066216e0dafe99',
    name: 'companyDetails',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Company Details',
    fields: [
      {
        id: '69d24e49f0066216e0dafe97',
        name: 'name',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Company Name',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafe98',
        name: 'tradeLicenseNumber',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Trade License Number',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafe9e',
    name: 'tradeLicense',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Trade License',
    fields: [
      {
        id: '69d24e49f0066216e0dafe9a',
        name: 'effectiveDate',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'date',
        label: 'Effective Date',
      },
      {
        id: '69d24e49f0066216e0dafe9b',
        name: 'expirationDate',
        width: null,
        required: true,
        defaultValue: null,
        blockName: null,
        blockType: 'date',
        label: 'Expiration Date',
      },
      {
        id: '69d24e49f0066216e0dafe9c',
        name: 'attachments',
        width: null,
        required: true,
        blockName: null,
        blockType: 'file',
        label: 'Attachments',
      },
      {
        id: '69d24e49f0066216e0dafe9d',
        name: 'description',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Description',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafea1',
    name: 'businessType',
    width: null,
    required: null,
    blockName: null,
    options: [
      {
        id: '69d24e49f0066216e0dafe9f',
        value: 'business',
        label: 'Business',
      },
      {
        id: '69d24e49f0066216e0dafea0',
        value: 'individual',
        label: 'Individual',
      },
    ],
    blockType: 'radio',
    label: 'Business Type',
    defaultValue: null,
  },
  {
    id: '69d24e49f0066216e0dafea2',
    name: 'countryOfIncorporation',
    width: null,
    required: null,
    blockName: null,
    blockType: 'text',
    label: 'Country of Incorporation',
    defaultValue: null,
  },
  {
    id: '69d24e49f0066216e0dafea3',
    name: 'establishmentDate',
    width: null,
    required: null,
    defaultValue: null,
    blockName: null,
    blockType: 'date',
    label: 'Establishment Date',
  },
  {
    id: '69d24e49f0066216e0dafea8',
    name: 'owner',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Owner Information',
    fields: [
      {
        id: '69d24e49f0066216e0dafea4',
        name: 'nationality',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Nationality',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafea5',
        name: 'dateOfBirth',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'date',
        label: 'Date of Birth',
      },
      {
        id: '69d24e49f0066216e0dafea6',
        name: 'passportNumber',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Passport Number',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafea7',
        name: 'passportCopy',
        width: null,
        required: true,
        blockName: null,
        blockType: 'file',
        label: 'Passport Copy',
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafeb3',
    name: 'shareholders',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Shareholders',
    fields: [
      {
        id: '69d24e49f0066216e0dafeab',
        name: 'hasCoOwners',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafea9',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafeaa',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Does the company have co-owners?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeac',
        name: 's2_nationality',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Co-Owner Nationality',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafead',
        name: 's2_dateOfBirth',
        width: null,
        required: null,
        blockName: null,
        blockType: 'date',
        label: 'Co-Owner Date of Birth',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeae',
        name: 's2_passportNumber',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Co-Owner Passport Number',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeaf',
        name: 's2_passportCopy',
        width: null,
        required: true,
        blockName: null,
        blockType: 'file',
        label: 'Co-Owner Passport Copy',
      },
      {
        id: '69d24e49f0066216e0dafeb2',
        name: 'hasAdditionalCoOwners',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafeb0',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafeb1',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Are there additional co-owners?',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafeb8',
    name: 'audit',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Audit & Financial Information',
    fields: [
      {
        id: '69d24e49f0066216e0dafeb4',
        name: 'auditorDetails',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Auditor Details',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeb5',
        name: 'turnover2024',
        width: null,
        defaultValue: null,
        required: null,
        blockName: null,
        blockType: 'number',
        label: 'Turnover 2024 (QAR)',
      },
      {
        id: '69d24e49f0066216e0dafeb6',
        name: 'turnover2025',
        width: null,
        defaultValue: null,
        required: null,
        blockName: null,
        blockType: 'number',
        label: 'Turnover 2025 (QAR)',
      },
      {
        id: '69d24e49f0066216e0dafeb7',
        name: 'currentMonthlyTurnover',
        width: null,
        defaultValue: null,
        required: null,
        blockName: null,
        blockType: 'number',
        label: 'Current Monthly Turnover',
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafed8',
    name: 'generalInfo',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'General Information',
    fields: [
      {
        id: '69d24e49f0066216e0dafeb9',
        name: 'jvPartners',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'JV Partners',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeba',
        name: 'associations',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Associations',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafebb',
        name: 'primaryBusinessDescription',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Primary Business Description',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafebc',
        name: 'middleEastBusinessDescription',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Middle East Business Description',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafebd',
        name: 'coreSkills',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Core Skills',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafebe',
        name: 'insuranceDetails',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Insurance Details',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafebf',
        name: 'insuranceClauses',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Insurance Clauses',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafec0',
        name: 'insurancePolicies',
        width: null,
        required: false,
        blockName: null,
        blockType: 'file',
        label: 'Insurance Policies',
      },
      {
        id: '69d24e49f0066216e0dafec3',
        name: 'parentCompanyGuarantee',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafec1',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafec2',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Parent Company Guarantee Available?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafec4',
        name: 'creditorReferences',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Creditor References (Name & Contact)',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafec5',
        name: 'subcontractorsAndSuppliers',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Subcontractors & Suppliers (Name & Details)',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafec6',
        name: 'orgChart',
        width: null,
        required: false,
        blockName: null,
        blockType: 'file',
        label: 'Organisation Chart',
      },
      {
        id: '69d24e49f0066216e0dafec7',
        name: 'staffTrainingInfo',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Staff Training Information',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafec8',
        name: 'inHouseShopDrawings',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'In-House Shop Drawings Capability',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafec9',
        name: 'localStaffCount',
        width: null,
        defaultValue: null,
        required: null,
        blockName: null,
        blockType: 'number',
        label: 'Local Staff Count',
      },
      {
        id: '69d24e49f0066216e0dafecc',
        name: 'hasQMS',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafeca',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafecb',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Do you have a Quality Management System (QMS)?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafecf',
        name: 'isLeedCompliant',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafecd',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafece',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Are you LEED compliant?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafed0',
        name: 'environmentalPolicy',
        width: null,
        required: false,
        blockName: null,
        blockType: 'file',
        label: 'Environmental Policy Document',
      },
      {
        id: '69d24e49f0066216e0dafed3',
        name: 'hasHAndSPolicy',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafed1',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafed2',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Do you have a Health & Safety Policy?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafed6',
        name: 'hasSafetyTraining',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafed4',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0dafed5',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Do you provide Safety Training?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafed7',
        name: 'siteInductionForm',
        width: null,
        required: false,
        blockName: null,
        blockType: 'file',
        label: 'Site Induction Form',
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafeeb',
    name: 'primaryContact',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Primary Contact',
    fields: [
      {
        id: '69d24e49f0066216e0dafed9',
        name: 'firstName',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'First Name',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeda',
        name: 'lastName',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Last Name',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafedb',
        name: 'email',
        width: null,
        required: true,
        blockName: null,
        blockType: 'email',
        label: 'Email',
      },
      {
        id: '69d24e49f0066216e0dafedc',
        name: 'fax',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Fax',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafedf',
        name: 'workPhone_type',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafedd',
            value: 'us_canada',
            label: 'US/Canada',
          },
          {
            id: '69d24e49f0066216e0dafede',
            value: 'other',
            label: 'Other',
          },
        ],
        blockType: 'radio',
        label: 'Work Phone Type',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee0',
        name: 'workPhone_countryCode',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Work Phone Country Code',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee1',
        name: 'workPhone_areaCode',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Work Phone Area Code',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee2',
        name: 'workPhone_localNumber',
        width: null,
        required: true,
        blockName: null,
        blockType: 'text',
        label: 'Work Phone Local Number',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee3',
        name: 'workPhone_extension',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Work Phone Extension',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee6',
        name: 'mobilePhone_type',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafee4',
            value: 'us_canada',
            label: 'US/Canada',
          },
          {
            id: '69d24e49f0066216e0dafee5',
            value: 'other',
            label: 'Other',
          },
        ],
        blockType: 'radio',
        label: 'Mobile Phone Type',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee7',
        name: 'mobilePhone_countryCode',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Mobile Country Code',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee8',
        name: 'mobilePhone_areaCode',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Mobile Area Code',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafee9',
        name: 'mobilePhone_localNumber',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Mobile Local Number',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafeea',
        name: 'mobilePhone_extension',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Mobile Extension',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafefd',
    name: 'primaryAddress',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Primary Address',
    fields: [
      {
        id: '69d24e49f0066216e0dafef1',
        name: 'purpose',
        width: null,
        placeholder: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafeec',
            value: 'hq',
            label: 'Headquarters',
          },
          {
            id: '69d24e49f0066216e0dafeed',
            value: 'branch',
            label: 'Branch',
          },
          {
            id: '69d24e49f0066216e0dafeee',
            value: 'registered',
            label: 'Registered',
          },
          {
            id: '69d24e49f0066216e0dafeef',
            value: 'billing',
            label: 'Billing',
          },
          {
            id: '69d24e49f0066216e0dafef0',
            value: 'shipping',
            label: 'Shipping',
          },
        ],
        blockType: 'select',
        label: 'Address Purpose',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef2',
        name: 'country',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Country',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef3',
        name: 'state',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'State',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef4',
        name: 'isoCode',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'ISO Code',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef5',
        name: 'name',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Address Name / Label',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef6',
        name: 'street1',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Street Line 1',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef7',
        name: 'street2',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Street Line 2',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef8',
        name: 'street3',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Street Line 3',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafef9',
        name: 'street4',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Street Line 4',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafefa',
        name: 'city',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'City',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafefb',
        name: 'postalCode',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Postal Code',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0dafefc',
        name: 'locationCode',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Location Code',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0dafefe',
    name: 'purchaseOrderEmail',
    width: null,
    required: null,
    blockName: null,
    blockType: 'email',
    label: 'Purchase Order Email',
  },
  {
    id: '69d24e49f0066216e0daff02',
    name: 'vat',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'VAT Information',
    fields: [
      {
        id: '69d24e49f0066216e0daff01',
        name: 'isRegistered',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0dafeff',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff00',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Are you VAT registered?',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff06',
    name: 'taxRegistrations',
    width: null,
    required: false,
    blockName: null,
    blockType: 'list',
    label: 'TAX Registrations',
    fields: [
      {
        id: '69d24e49f0066216e0daff03',
        name: 'vatID',
        width: null,
        required: false,
        blockName: null,
        blockType: 'text',
        label: 'VAT ID',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff04',
        name: 'country',
        width: null,
        required: false,
        blockName: null,
        blockType: 'text',
        label: 'Country',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff05',
        name: 'local',
        width: null,
        required: false,
        defaultValue: false,
        blockName: null,
        blockType: 'checkbox',
        label: 'Local',
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff0b',
    name: 'vatCertificate',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'VAT Certificate',
    fields: [
      {
        id: '69d24e49f0066216e0daff07',
        name: 'effectiveDate',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Effective Date',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff08',
        name: 'expirationDate',
        width: null,
        required: null,
        blockName: null,
        blockType: 'text',
        label: 'Expiration Date',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff09',
        name: 'attachments',
        width: null,
        required: false,
        blockName: null,
        blockType: 'file',
        label: 'VAT Certificate Attachment',
      },
      {
        id: '69d24e49f0066216e0daff0a',
        name: 'description',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'Description',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff0e',
    name: 'isBasedInEgypt',
    width: null,
    required: null,
    blockName: null,
    options: [
      {
        id: '69d24e49f0066216e0daff0c',
        value: 'yes',
        label: 'Yes',
      },
      {
        id: '69d24e49f0066216e0daff0d',
        value: 'no',
        label: 'No',
      },
    ],
    blockType: 'radio',
    label: 'Is the company based in Egypt?',
    defaultValue: null,
  },
  {
    id: '69d24e49f0066216e0daff11',
    name: 'isBasedInKuwait',
    width: null,
    required: null,
    blockName: null,
    options: [
      {
        id: '69d24e49f0066216e0daff0f',
        value: 'yes',
        label: 'Yes',
      },
      {
        id: '69d24e49f0066216e0daff10',
        value: 'no',
        label: 'No',
      },
    ],
    blockType: 'radio',
    label: 'Is the company based in Kuwait?',
    defaultValue: null,
  },
  {
    id: '69d24e49f0066216e0daff15',
    name: 'banking',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Banking',
    fields: [
      {
        id: '69d24e49f0066216e0daff14',
        name: 'createOrDeactivate',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff12',
            value: 'create',
            label: 'Create',
          },
          {
            id: '69d24e49f0066216e0daff13',
            value: 'deactivate',
            label: 'Deactivate',
          },
        ],
        blockType: 'radio',
        label: 'Create or Deactivate Bank Account?',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff25',
    name: 'declaration',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Declaration',
    fields: [
      {
        id: '69d24e49f0066216e0daff18',
        name: 'legalActions',
        width: null,
        required: true,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff16',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff17',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Are there any pending legal actions against the company?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff1b',
        name: 'liquidatedPersonnel',
        width: null,
        required: true,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff19',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff1a',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Has any key personnel been liquidated?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff1e',
        name: 'litigationClaims',
        width: null,
        required: true,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff1c',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff1d',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Are there any active litigation claims?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff1f',
        blockName: null,
        blockType: 'message',
        message: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Download NDA ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 8,
                        mode: 'normal',
                        style: '',
                        text: 'here',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: null,
                    fields: {
                      linkType: 'custom',
                      newTab: true,
                      url: 'https://dohaoasis.com/',
                    },
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                  },
                ],
                direction: null,
                format: 'left',
                indent: 0,
                type: 'paragraph',
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      {
        id: '69d24e49f0066216e0daff20',
        name: 'signedNda',
        width: null,
        required: true,
        blockName: null,
        blockType: 'file',
        label: 'Signed NDA',
      },
      {
        id: '69d24e49f0066216e0daff23',
        name: 'agreeNda',
        width: null,
        required: true,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff21',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff22',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Do you agree to the NDA?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff24',
        name: 'ndaDisagreementReason',
        width: null,
        required: null,
        blockName: null,
        blockType: 'textarea',
        label: 'NDA Disagreement Reason (if applicable)',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff28',
    name: 'statement',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Statement',
    fields: [
      {
        id: '69d24e49f0066216e0daff26',
        blockName: null,
        blockType: 'message',
        message: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Download code of conduct ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 8,
                        mode: 'normal',
                        style: '',
                        text: 'here',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: null,
                    fields: {
                      linkType: 'custom',
                      newTab: true,
                      url: 'https://dohaoasis.com/',
                    },
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                  },
                ],
                direction: null,
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      {
        id: '69d24e49f0066216e0daff27',
        name: 'agreeToTaxInvoicing',
        width: null,
        required: true,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label: 'I agree to the tax invoicing terms.',
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff38',
    name: 'conflictOfInterest',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Conflict of Interest',
    fields: [
      {
        id: '69d24e49f0066216e0daff29',
        blockName: null,
        blockType: 'message',
        message: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Download sustainability ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 8,
                        mode: 'normal',
                        style: '',
                        text: 'here',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: '.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: null,
                    fields: {
                      linkType: 'custom',
                      newTab: true,
                      url: 'https://dohaoasis.com/',
                    },
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                  },
                ],
                direction: null,
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
              },
            ],
            direction: null,
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      {
        id: '69d24e49f0066216e0daff2c',
        name: 'prevEmployeeDOA',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff2a',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff2b',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Were you previously employed by Doha Oasis?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff2f',
        name: 'relatedToDOAStaff',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff2d',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff2e',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Are you related to any Doha Oasis staff?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff30',
        name: 'noConflictDeclaration',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label: 'I declare there is no conflict of interest.',
      },
      {
        id: '69d24e49f0066216e0daff31',
        name: 'noManagementRelationship',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label: 'I declare no management relationship with Doha Oasis.',
      },
      {
        id: '69d24e49f0066216e0daff32',
        name: 'noPrevManagementInDOA',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label: 'I confirm no previous management role in Doha Oasis.',
      },
      {
        id: '69d24e49f0066216e0daff33',
        name: 'noAssociations',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label: 'I confirm no undisclosed associations.',
      },
      {
        id: '69d24e49f0066216e0daff34',
        name: 'noAffiliatedCompanies',
        width: null,
        required: null,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label: 'I confirm no affiliated companies with Doha Oasis.',
      },
      {
        id: '69d24e49f0066216e0daff37',
        name: 'summaryTrigger',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff35',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff36',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Does any of the above apply?',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff42',
    name: 'connectedPersons',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Connected Persons',
    fields: [
      {
        id: '69d24e49f0066216e0daff3b',
        name: 'fourthDegreeKinship',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff39',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff3a',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Any connected persons within 4th degree of kinship?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff3e',
        name: 'unincorporatedPartnership',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff3c',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff3d',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Any unincorporated partnerships?',
        defaultValue: null,
      },
      {
        id: '69d24e49f0066216e0daff41',
        name: 'doaControlInterest',
        width: null,
        required: null,
        blockName: null,
        options: [
          {
            id: '69d24e49f0066216e0daff3f',
            value: 'yes',
            label: 'Yes',
          },
          {
            id: '69d24e49f0066216e0daff40',
            value: 'no',
            label: 'No',
          },
        ],
        blockType: 'radio',
        label: 'Does Doha Oasis hold a controlling interest?',
        defaultValue: null,
      },
    ],
  },
  {
    id: '69d24e49f0066216e0daff44',
    name: 'finalDeclaration',
    width: null,
    required: false,
    blockName: null,
    blockType: 'group',
    label: 'Final Declaration',
    fields: [
      {
        id: '69d24e49f0066216e0daff43',
        name: 'truthConfirmation',
        width: null,
        required: true,
        defaultValue: null,
        blockName: null,
        blockType: 'checkbox',
        label:
          'I confirm that all information provided is true and accurate to the best of my knowledge.',
      },
    ],
  },
]
