import type { Payload } from 'payload'
import type { TripSchedulingShuttle } from '@/payload-types'
import { emptySeedCount, type SeedCount } from './helpers/create-if-missing'

export type ShuttleSeedCount = SeedCount & { warnings: string[] }

export const seedTripSchedulingShuttles = async (payload: Payload): Promise<ShuttleSeedCount> => {
  payload.logger.info('  └─ Seeding Master Shuttle Timeline Entries...')

  const isDev = process.env.NODE_ENV !== 'production'

  // 🛡️ Safeguard: Only purge in development if explicitly desired
  // In production, this block is skipped automatically!
  if (isDev && process.env.RESET_SEED_DATA === 'true') {
    try {
      await payload.delete({
        collection: 'trip-scheduling-shuttles',
        where: { id: { exists: true } },
        overrideAccess: true,
      })
      payload.logger.info('  └─ [DEV] Cleared existing schedules prior to seeding.')
    } catch (err) {
      payload.logger.warn('  └─ [DEV] Pre-seed cleanup skipped or collection empty.')
    }
  }

  const shuttleSchedules: Array<{
    direction: TripSchedulingShuttle['direction']
    routeName: string
    departureTime: string
    arrivalTime: string
    pickupManager: number
    pickupMale: number
    pickupFemale: number
    pickupGeneral: number
    vehicleName: string
    publicNote: string
  }> = [
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '05:30',
      arrivalTime: '06:10',
      pickupManager: 530,
      pickupMale: 535,
      pickupFemale: 540,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '06:30',
      arrivalTime: '06:45',
      pickupManager: 630,
      pickupMale: 635,
      pickupFemale: 640,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '07:25',
      arrivalTime: '07:45',
      pickupManager: 725,
      pickupMale: 730,
      pickupFemale: 735,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '08:10',
      arrivalTime: '08:30',
      pickupManager: 810,
      pickupMale: 815,
      pickupFemale: 820,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '08:40',
      arrivalTime: '09:00',
      pickupManager: 840,
      pickupMale: 845,
      pickupFemale: 850,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '09:10',
      arrivalTime: '09:30',
      pickupManager: 910,
      pickupMale: 915,
      pickupFemale: 920,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '09:40',
      arrivalTime: '10:00',
      pickupManager: 940,
      pickupMale: 945,
      pickupFemale: 950,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '10:10',
      arrivalTime: '10:30',
      pickupManager: 1010,
      pickupMale: 1015,
      pickupFemale: 1020,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '10:40',
      arrivalTime: '11:00',
      pickupManager: 1040,
      pickupMale: 1045,
      pickupFemale: 1050,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '11:15',
      arrivalTime: '11:45',
      pickupManager: 1115,
      pickupMale: 1120,
      pickupFemale: 1130,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '12:10',
      arrivalTime: '12:30',
      pickupManager: 1210,
      pickupMale: 1215,
      pickupFemale: 1220,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '12:40',
      arrivalTime: '13:10',
      pickupManager: 1240,
      pickupMale: 1245,
      pickupFemale: 1250,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '13:40',
      arrivalTime: '14:10',
      pickupManager: 1340,
      pickupMale: 1345,
      pickupFemale: 1350,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '14:40',
      arrivalTime: '15:10',
      pickupManager: 1440,
      pickupMale: 1445,
      pickupFemale: 1445,
      pickupGeneral: 0,
      vehicleName: 'Bus 01 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '13:05',
      arrivalTime: '13:35',
      pickupManager: 1305,
      pickupMale: 1310,
      pickupFemale: 1315,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '14:10',
      arrivalTime: '14:35',
      pickupManager: 1410,
      pickupMale: 1415,
      pickupFemale: 1420,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '15:05',
      arrivalTime: '15:35',
      pickupManager: 1505,
      pickupMale: 1510,
      pickupFemale: 1515,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '17:10',
      arrivalTime: '18:15',
      pickupManager: 1710,
      pickupMale: 1715,
      pickupFemale: 1720,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '18:40',
      arrivalTime: '18:55',
      pickupManager: 1840,
      pickupMale: 1845,
      pickupFemale: 1850,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '22:20',
      arrivalTime: '22:45',
      pickupManager: 2220,
      pickupMale: 2225,
      pickupFemale: 2230,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '16:10',
      arrivalTime: '16:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '21:15',
      arrivalTime: '21:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 2130,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '21:40',
      arrivalTime: '21:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '23:15',
      arrivalTime: '23:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 02 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '16:40',
      arrivalTime: '17:10',
      pickupManager: 1640,
      pickupMale: 1645,
      pickupFemale: 1650,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: 'Engineering & Support Team',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '17:40',
      arrivalTime: '18:15',
      pickupManager: 1740,
      pickupMale: 1745,
      pickupFemale: 1750,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: 'Engineering & Support Team',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '19:15',
      arrivalTime: '19:45',
      pickupManager: 1915,
      pickupMale: 1925,
      pickupFemale: 1930,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: 'Engineering & Support Team',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '23:25',
      arrivalTime: '23:45',
      pickupManager: 2325,
      pickupMale: 2330,
      pickupFemale: 2335,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '16:10',
      arrivalTime: '16:10',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '21:30',
      arrivalTime: '21:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 2130,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '22:15',
      arrivalTime: '22:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '00:15',
      arrivalTime: '00:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '00:45',
      arrivalTime: '00:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '01:15',
      arrivalTime: '01:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '01:45',
      arrivalTime: '01:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Al Sadd)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Al Sadd',
      departureTime: '07:15',
      arrivalTime: '07:30',
      pickupManager: 0,
      pickupMale: 715,
      pickupFemale: 720,
      pickupGeneral: 0,
      vehicleName: 'Van 01 (Al Sadd)',
      publicNote: 'KIEN',
    },
    {
      direction: 'from-office',
      routeName: 'Al Sadd',
      departureTime: '00:15',
      arrivalTime: '00:35',
      pickupManager: 0,
      pickupMale: 25,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Van 02 (Al Sadd)',
      publicNote: 'Male | Engineering',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '05:10',
      arrivalTime: '05:20',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 510,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '05:25',
      arrivalTime: '05:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 525,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '06:55',
      arrivalTime: '07:05',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 655,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '07:10',
      arrivalTime: '07:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 710,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '07:25',
      arrivalTime: '07:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 725,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '07:45',
      arrivalTime: '07:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 745,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '08:05',
      arrivalTime: '08:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 805,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '09:15',
      arrivalTime: '09:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 915,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '10:15',
      arrivalTime: '10:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1015,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '11:15',
      arrivalTime: '11:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1115,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '12:15',
      arrivalTime: '12:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1215,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '12:30',
      arrivalTime: '12:40',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1230,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '12:45',
      arrivalTime: '12:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1245,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '13:15',
      arrivalTime: '13:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1315,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '13:30',
      arrivalTime: '13:40',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1330,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '14:15',
      arrivalTime: '14:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1415,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '15:15',
      arrivalTime: '15:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1515,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '15:50',
      arrivalTime: '16:10',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1550,
      vehicleName: 'Bus 01 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '07:10',
      arrivalTime: '07:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 710,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '07:25',
      arrivalTime: '07:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 725,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '07:45',
      arrivalTime: '07:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 745,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '08:45',
      arrivalTime: '08:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 845,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '09:45',
      arrivalTime: '09:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 945,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '10:30',
      arrivalTime: '10:40',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1030,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '11:30',
      arrivalTime: '11:40',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1130,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '12:15',
      arrivalTime: '12:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1215,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '12:45',
      arrivalTime: '12:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1245,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '13:15',
      arrivalTime: '13:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1315,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '13:45',
      arrivalTime: '13:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1345,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '14:20',
      arrivalTime: '14:40',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1420,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '14:45',
      arrivalTime: '15:05',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1445,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '15:30',
      arrivalTime: '15:55',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1530,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '16:15',
      arrivalTime: '16:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1615,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '17:15',
      arrivalTime: '17:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1715,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '17:40',
      arrivalTime: '17:50',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1740,
      vehicleName: 'Bus 02 (Yasameen)',
      publicNote: 'BUS 2 Final Inbound Track',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '14:20',
      arrivalTime: '16:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1420,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '17:15',
      arrivalTime: '17:25',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1715,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '18:10',
      arrivalTime: '18:20',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1810,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'to-office',
      routeName: 'Yasameen',
      departureTime: '19:25',
      arrivalTime: '19:40',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 1925,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '19:10',
      arrivalTime: '19:10',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '20:05',
      arrivalTime: '20:05',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '20:20',
      arrivalTime: '20:20',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '21:10',
      arrivalTime: '21:10',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '21:25',
      arrivalTime: '21:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 2125,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '21:50',
      arrivalTime: '22:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 2150,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '22:25',
      arrivalTime: '22:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 2225,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '22:50',
      arrivalTime: '22:50',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '23:15',
      arrivalTime: '23:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '23:25',
      arrivalTime: '23:35',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 2325,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '00:15',
      arrivalTime: '00:15',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 0,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '00:35',
      arrivalTime: '00:50',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 35,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '01:05',
      arrivalTime: '01:20',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 105,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '01:35',
      arrivalTime: '01:50',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 135,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '03:30',
      arrivalTime: '03:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 330,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: 'LC Male Drop (La Cigale Staff)',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '03:40',
      arrivalTime: '03:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 340,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: 'Building 8 Accommodation',
    },
    {
      direction: 'from-office',
      routeName: 'Yasameen',
      departureTime: '02:25',
      arrivalTime: '02:45',
      pickupManager: 0,
      pickupMale: 0,
      pickupFemale: 0,
      pickupGeneral: 225,
      vehicleName: 'Bus 03 (Yasameen)',
      publicNote: '',
    },
  ]

  const count: ShuttleSeedCount = { ...emptySeedCount(), warnings: [] }

  // A shuttle has no stable identity besides its time (which admins edit), so seeding works per
  // route: a route that already has any shuttles is left untouched.
  const routeIds = new Map<string, string | null>()
  const routesToSeed = new Set<string>()
  for (const routeName of new Set(shuttleSchedules.map((s) => s.routeName))) {
    const routeDoc = await payload.find({
      collection: 'trip-scheduling-routes',
      where: { name: { equals: routeName } },
      limit: 1,
      depth: 0,
      overrideAccess: true,
    })
    const routeId = routeDoc.docs[0]?.id ?? null
    routeIds.set(routeName, routeId)
    if (!routeId) continue

    const existing = await payload.find({
      collection: 'trip-scheduling-shuttles',
      where: { route: { equals: routeId } },
      limit: 1,
      depth: 0,
      overrideAccess: true,
    })
    if (existing.docs.length === 0) routesToSeed.add(routeName)
  }

  for (const s of shuttleSchedules) {
    const routeId = routeIds.get(s.routeName)
    if (routeId && !routesToSeed.has(s.routeName)) {
      count.skipped++
      continue
    }

    const vehicleDoc = routeId
      ? await payload.find({
          collection: 'trip-scheduling-vehicles',
          where: { name: { equals: s.vehicleName } },
          limit: 1,
          overrideAccess: true,
        })
      : null
    const vehicleId = vehicleDoc?.docs[0]?.id
    // route and vehicle are required: skip the row rather than create it half-linked
    if (!routeId || !vehicleId) {
      const warning = `Skipped ${s.direction} ${s.departureTime} shuttle: ${!routeId ? `route "${s.routeName}"` : `vehicle "${s.vehicleName}"`} not found`
      payload.logger.warn(`  └─ ${warning}`)
      count.skipped++
      count.warnings.push(warning)
      continue
    }

    await payload.create({
      collection: 'trip-scheduling-shuttles',
      data: {
        direction: s.direction,
        route: routeId,
        vehicle: vehicleId,
        departureTime: s.departureTime,
        arrivalTime: s.arrivalTime,
        pickupManager: s.pickupManager,
        pickupMale: s.pickupMale,
        pickupFemale: s.pickupFemale,
        pickupGeneral: s.pickupGeneral,
        publicNote: s.publicNote,
      },
      overrideAccess: true,
    })
    count.created++
  }

  payload.logger.info('  └─ Shuttle Schedules seeding completed safely!')
  return count
}
