import { Payload } from 'payload'
import { createIfMissing, emptySeedCount, type SeedCount } from './helpers/create-if-missing'

export const seedTripSchedulingZones = async (payload: Payload): Promise<SeedCount> => {
  payload.logger.info('  └─ Seeding 87 Qatar Operational Zones & Districts...')

  const qatarZones = [
    { indexNumber: 1, zoneNumber: '1', district: 'Al Jasrah', tripCost: 30, isActive: true },
    {
      indexNumber: 2,
      zoneNumber: '2',
      district: 'Al Bidda / Souq Waqif',
      tripCost: 30,
      isActive: true,
    },
    {
      indexNumber: 3,
      zoneNumber: '3',
      district: 'Mohamed Bin Jasim / Al Souq',
      tripCost: 30,
      isActive: true,
    },
    { indexNumber: 4, zoneNumber: '4', district: 'Mushayrib', tripCost: 30, isActive: true },
    {
      indexNumber: 5,
      zoneNumber: '5',
      district: 'Al Najada / Rumeilah',
      tripCost: 35,
      isActive: true,
    },
    {
      indexNumber: 6,
      zoneNumber: '6',
      district: 'Barahat Al Jufairi / Dafna',
      tripCost: 35,
      isActive: true,
    },
    { indexNumber: 7, zoneNumber: '7', district: 'Old Al Ghanim', tripCost: 0, isActive: false },
    { indexNumber: 9, zoneNumber: '9', district: 'New Salata', tripCost: 35, isActive: true },
    { indexNumber: 10, zoneNumber: '10', district: 'Al Souq', tripCost: 0, isActive: false },
    { indexNumber: 11, zoneNumber: '11', district: 'Al Khulaifat', tripCost: 0, isActive: false },
    { indexNumber: 12, zoneNumber: '12', district: 'Al Hitmi', tripCost: 0, isActive: false },
    {
      indexNumber: 13,
      zoneNumber: '13',
      district: 'Mirqab Al Jadeed / Musheireb',
      tripCost: 20,
      isActive: true,
    },
    { indexNumber: 14, zoneNumber: '14', district: 'As Salatah', tripCost: 0, isActive: false },
    { indexNumber: 15, zoneNumber: '15', district: 'Al Mirqab', tripCost: 0, isActive: false },
    { indexNumber: 16, zoneNumber: '16', district: 'Ar Rifa', tripCost: 0, isActive: false },
    { indexNumber: 17, zoneNumber: '17', district: 'Old Al Hitmi', tripCost: 0, isActive: false },
    { indexNumber: 18, zoneNumber: '18', district: 'As Satahn', tripCost: 0, isActive: false },
    { indexNumber: 20, zoneNumber: '20', district: 'Wadi Al Sail', tripCost: 0, isActive: false },
    { indexNumber: 21, zoneNumber: '21', district: 'Ar Rumeilah', tripCost: 0, isActive: false },
    {
      indexNumber: 22,
      zoneNumber: '22',
      district: 'Bin Mahmoud (Doha Oasis)',
      tripCost: 15,
      isActive: true,
    },
    {
      indexNumber: 23,
      zoneNumber: '23',
      district: 'Rawdat Al Khail / Al Muntazah',
      tripCost: 25,
      isActive: true,
    },
    {
      indexNumber: 24,
      zoneNumber: '24',
      district: 'Fereej Abdul Aziz / Al Muntazah',
      tripCost: 20,
      isActive: true,
    },
    { indexNumber: 25, zoneNumber: '25', district: 'Al Mansoura', tripCost: 30, isActive: true },
    { indexNumber: 26, zoneNumber: '26', district: 'Najma', tripCost: 30, isActive: true },
    { indexNumber: 27, zoneNumber: '27', district: 'Umm Ghuwailina', tripCost: 30, isActive: true },
    {
      indexNumber: 28,
      zoneNumber: '28',
      district: 'Al Doha Al Jadeeda / Al Khulaifat (South)',
      tripCost: 20,
      isActive: true,
    },
    { indexNumber: 30, zoneNumber: '30', district: 'Duhail', tripCost: 0, isActive: false },
    {
      indexNumber: 31,
      zoneNumber: '31',
      district: 'Umm Lekhba / Nuaija',
      tripCost: 25,
      isActive: true,
    },
    {
      indexNumber: 32,
      zoneNumber: '32',
      district: 'Madinat Khalifa (North)',
      tripCost: 0,
      isActive: false,
    },
    { indexNumber: 33, zoneNumber: '33', district: 'Al Markhiya', tripCost: 0, isActive: false },
    {
      indexNumber: 34,
      zoneNumber: '34',
      district: 'Madinat Khalifa (South)',
      tripCost: 0,
      isActive: false,
    },
    {
      indexNumber: 35,
      zoneNumber: '35',
      district: 'Kulaib / Airport Area',
      tripCost: 45,
      isActive: true,
    },
    { indexNumber: 36, zoneNumber: '36', district: 'Al Messila', tripCost: 0, isActive: false },
    {
      indexNumber: 37,
      zoneNumber: '37',
      district: 'Fereej Bin Omran',
      tripCost: 0,
      isActive: false,
    },
    {
      indexNumber: 38,
      zoneNumber: '38',
      district: 'Al Sadd / Al Hitmi (New)',
      tripCost: 20,
      isActive: true,
    },
    {
      indexNumber: 39,
      zoneNumber: '39',
      district: 'Al Mirqab Al Jadeed / Fereej Bin Omran',
      tripCost: 25,
      isActive: true,
    },
    { indexNumber: 40, zoneNumber: '40', district: 'Al Thumama', tripCost: 0, isActive: false },
    {
      indexNumber: 41,
      zoneNumber: '41',
      district: 'Nuaija / Madinat Khalifa South',
      tripCost: 35,
      isActive: true,
    },
    { indexNumber: 42, zoneNumber: '42', district: 'Al Hilal', tripCost: 30, isActive: true },
    {
      indexNumber: 43,
      zoneNumber: '43',
      district: 'Al Maamoura / Al Messila',
      tripCost: 25,
      isActive: true,
    },
    {
      indexNumber: 44,
      zoneNumber: '44',
      district: 'Nuaija (West) / Fereej Kulaib',
      tripCost: 30,
      isActive: true,
    },
    {
      indexNumber: 45,
      zoneNumber: '45',
      district: 'The Pearl-Qatar / Old Airport',
      tripCost: 40,
      isActive: true,
    },
    { indexNumber: 46, zoneNumber: '46', district: 'Al Thumama', tripCost: 40, isActive: true },
    {
      indexNumber: 47,
      zoneNumber: '47',
      district: 'Al Thumama (South)',
      tripCost: 45,
      isActive: true,
    },
    {
      indexNumber: 48,
      zoneNumber: '48',
      district: 'Duhail / Industrial Area',
      tripCost: 45,
      isActive: true,
    },
    {
      indexNumber: 49,
      zoneNumber: '49',
      district: 'Umm Lekhba / Industrial Area Extension',
      tripCost: 45,
      isActive: true,
    },
    {
      indexNumber: 50,
      zoneNumber: '50',
      district: 'Al Markhiya / Old Airport',
      tripCost: 35,
      isActive: true,
    },
    { indexNumber: 51, zoneNumber: '51', district: 'Al Gharrafa', tripCost: 40, isActive: true },
    { indexNumber: 52, zoneNumber: '52', district: 'Izghawa', tripCost: 45, isActive: true },
    { indexNumber: 53, zoneNumber: '53', district: 'Al Rayyan', tripCost: 50, isActive: true },
    { indexNumber: 54, zoneNumber: '54', district: 'Bu Hamour', tripCost: 50, isActive: true },
    { indexNumber: 55, zoneNumber: '55', district: 'Al Waab', tripCost: 30, isActive: true },
    {
      indexNumber: 56,
      zoneNumber: '56',
      district: 'Ain Khaled / Mesaimeer',
      tripCost: 40,
      isActive: true,
    },
    { indexNumber: 57, zoneNumber: '57', district: 'Abu Sidra', tripCost: 40, isActive: true },
    { indexNumber: 60, zoneNumber: '60', district: 'Al Daayen', tripCost: 0, isActive: false },
    {
      indexNumber: 61,
      zoneNumber: '61',
      district: 'West Bay / Al Sakhama',
      tripCost: 25,
      isActive: true,
    },
    {
      indexNumber: 62,
      zoneNumber: '62',
      district: 'Rawdat Al Hamama',
      tripCost: 0,
      isActive: false,
    },
    {
      indexNumber: 63,
      zoneNumber: '63',
      district: 'Legtaifiya / Umm Qarn',
      tripCost: 25,
      isActive: true,
    },
    {
      indexNumber: 64,
      zoneNumber: '64',
      district: 'Al Qassar / Al Khor',
      tripCost: 25,
      isActive: true,
    },
    { indexNumber: 65, zoneNumber: '65', district: 'Simaisma', tripCost: 0, isActive: false },
    {
      indexNumber: 66,
      zoneNumber: '66',
      district: 'Onaiza / The Pearl / Al Qatariya',
      tripCost: 35,
      isActive: true,
    },
    { indexNumber: 67, zoneNumber: '67', district: 'Al Dhakira', tripCost: 0, isActive: false },
    {
      indexNumber: 68,
      zoneNumber: '68',
      district: 'Al Kheesa / Al Ras',
      tripCost: 35,
      isActive: true,
    },
    {
      indexNumber: 69,
      zoneNumber: '69',
      district: 'Lusail / Al Thakhira',
      tripCost: 40,
      isActive: true,
    },
    {
      indexNumber: 70,
      zoneNumber: '70',
      district: 'Umm Salal Mohammed / Al Kheesa',
      tripCost: 50,
      isActive: true,
    },
    { indexNumber: 71, zoneNumber: '71', district: 'Umm Salal Ali', tripCost: 60, isActive: true },
    {
      indexNumber: 72,
      zoneNumber: '72',
      district: 'Al Daayen / Umm Salal Mohammed',
      tripCost: 70,
      isActive: true,
    },
    {
      indexNumber: 73,
      zoneNumber: '73',
      district: 'Simaisma / Sna Al-Humaidi',
      tripCost: 80,
      isActive: true,
    },
    {
      indexNumber: 74,
      zoneNumber: '74',
      district: 'Al Khor / Al Khuraitiyat',
      tripCost: 90,
      isActive: true,
    },
    {
      indexNumber: 75,
      zoneNumber: '75',
      district: 'Al Thakhira / Al Kharaitiyat (North)',
      tripCost: 100,
      isActive: true,
    },
    { indexNumber: 76, zoneNumber: '76', district: 'Umm Al Amad', tripCost: 0, isActive: false },
    { indexNumber: 77, zoneNumber: '77', district: 'Umm Ebairiya', tripCost: 0, isActive: false },
    {
      indexNumber: 79,
      zoneNumber: '79',
      district: 'Hamad International Airport',
      tripCost: 50,
      isActive: true,
    },
    { indexNumber: 80, zoneNumber: '80', district: 'Ash-Shahaniya', tripCost: 0, isActive: false },
    {
      indexNumber: 81,
      zoneNumber: '81',
      district: 'Industrial Area / Al Utouriya',
      tripCost: 60,
      isActive: true,
    },
    {
      indexNumber: 82,
      zoneNumber: '82',
      district: 'Abu Nakhla / Al Jamilaniya',
      tripCost: 70,
      isActive: true,
    },
    {
      indexNumber: 83,
      zoneNumber: '83',
      district: 'Muaither / Al Sulaimiya',
      tripCost: 40,
      isActive: true,
    },
    {
      indexNumber: 84,
      zoneNumber: '84',
      district: 'Al Wajba / Rawdat Rashed',
      tripCost: 50,
      isActive: true,
    },
    {
      indexNumber: 85,
      zoneNumber: '85',
      district: 'Al Shahaniya / Umm Bab',
      tripCost: 80,
      isActive: true,
    },
    {
      indexNumber: 86,
      zoneNumber: '86',
      district: 'Dukhan / Al Nasraniya',
      tripCost: 100,
      isActive: true,
    },
    { indexNumber: 87, zoneNumber: '87', district: 'Umm Bab', tripCost: 160, isActive: true },
    { indexNumber: 90, zoneNumber: '90', district: 'Al Wakrah', tripCost: 80, isActive: true },
    {
      indexNumber: 91,
      zoneNumber: '91',
      district: 'Mesaieed / Al Wukair',
      tripCost: 130,
      isActive: true,
    },
    {
      indexNumber: 92,
      zoneNumber: '92',
      district: 'Al Wukair / Al Mashaf',
      tripCost: 120,
      isActive: true,
    },
    {
      indexNumber: 93,
      zoneNumber: '93',
      district: 'Al Mashaf / Mesaieed Industrial Area',
      tripCost: 130,
      isActive: true,
    },
    {
      indexNumber: 94,
      zoneNumber: '94',
      district: 'Al Karaana / Shagra',
      tripCost: 160,
      isActive: true,
    },
    { indexNumber: 95, zoneNumber: '95', district: 'Al Kharrara', tripCost: 180, isActive: true },
    {
      indexNumber: 96,
      zoneNumber: '96',
      district: 'Al Sheehaniya / Sealine',
      tripCost: 200,
      isActive: true,
    },
    { indexNumber: 97, zoneNumber: '97', district: 'Umm Hulw', tripCost: 0, isActive: false },
    {
      indexNumber: 98,
      zoneNumber: '98',
      district: 'Mesaieed Colony',
      tripCost: 0,
      isActive: false,
    },
  ]

  const count = emptySeedCount()
  for (const z of qatarZones) {
    count[
      await createIfMissing(payload, 'trip-scheduling-zones', { zoneNumber: { equals: z.zoneNumber } }, z)
    ]++
  }
  return count
}
