import CreatedByField from '@/common/fields/created-by'
import UpdatedByField from '@/common/fields/updated-by'
import { setOperatorSlugCollection } from '@/common/hooks/operator-slug-update'
import { setUserCreatedOrUpdatedByCollection } from '@/common/hooks/user-update'
import { auditLogAfterChange, auditLogAfterDelete } from '@/common/hooks/audit-log'
import { User } from '@/payload-types'
import { filterByOperator } from '@/utilities/filter-by-operator'
import {
  surveyInvitationsAccess,
  surveyInvitationsAdminAccess,
  surveyInvitationsCreateAccess,
  surveyInvitationsHidden,
} from './access'
import { CollectionConfig, FieldAccess, TextFieldValidation } from 'payload'

const SLUG = 'survey-invitations'

// Simple RFC-5322-ish email check. No existing email validator util in src/utilities/ to reuse.
const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

const validateEmail: TextFieldValidation = (value) => {
  if (typeof value !== 'string' || !value.trim()) {
    return 'Email is required'
  }
  if (!EMAIL_REGEX.test(value.trim())) {
    return 'Please enter a valid email address'
  }
  return true
}

// Anonymity: only super users may see (or change) who an invitation went to. Internal paths
// (send job, resend, survey gate) read with overrideAccess, so they are unaffected.
const superUserOnly: FieldAccess = ({ req }) =>
  Boolean((req.user as unknown as User | null)?.super_user)

const SurveyInvitations: CollectionConfig = {
  slug: SLUG,
  labels: { plural: 'Survey Invitations', singular: 'Survey Invitation' },
  admin: {
    group: 'Surveys',
    // Not `email`: the title shows in breadcrumbs and the browser tab for every reader.
    useAsTitle: 'code',
    defaultColumns: ['email', 'form', 'department', 'code', 'status', 'sent_at', 'resend'],
    // Code only: a search that includes `email` fails outright for users who can't query it.
    // Super users can still filter by email from the list's Filters panel.
    listSearchableFields: ['code'],
    description:
      'One record per invited recipient. Only super users can see the recipient email. ' +
      'The email↔code mapping lives only here — ' +
      '`form-submissions` stores the invitation code but never the email. This makes responses ' +
      'pseudonymous, not cryptographically anonymous: an administrator with read access to both ' +
      'this collection and `form-submissions` (and to the audit log, which records the ' +
      'sent → responded transition with the email present) can still link a response back to its ' +
      'recipient via the shared code. Treat "anonymous" language to respondents with that caveat ' +
      'in mind.',
    hidden: (u) => surveyInvitationsHidden(u.user as unknown as User),
  },
  fields: [
    {
      type: 'relationship',
      name: 'form',
      label: 'Form',
      relationTo: 'forms',
      required: true,
      filterOptions: {
        is_survey: { equals: true },
      },
    },
    {
      type: 'text',
      name: 'email',
      label: 'Email',
      required: true,
      validate: validateEmail,
      access: {
        read: superUserOnly,
        update: superUserOnly,
      },
      // Stored lowercased so the (form, email) dedupe in `survey-invitation-send` is case-insensitive.
      hooks: {
        beforeValidate: [
          ({ value }) => (typeof value === 'string' ? value.trim().toLowerCase() : value),
        ],
      },
    },
    {
      type: 'text',
      name: 'code',
      label: 'Code',
      required: true,
      index: true,
      admin: {
        readOnly: true,
        description:
          'Generated by the bulk-send action. Format is <random 6 chars>-<survey code>, e.g. ' +
          'ABC123-A1, where the A1 suffix is this survey form\'s own code. Unique per form, not ' +
          'globally — the same code may exist under a different form. Single-use: the code stops ' +
          'working the moment a submission ' +
          'for it is saved (status flips to Responded); a submission that fails after the code is ' +
          'claimed automatically restores the code to reusable rather than burning it.',
      },
    },
    {
      type: 'select',
      name: 'status',
      label: 'Status',
      defaultValue: 'pending',
      admin: {
        description:
          '"Responded" means the code has been used and a submission was saved for it — it can never ' +
          'be reused, even by the same recipient. "Pending"/"Sent" codes are still valid; "Error" ' +
          'means the invitation email itself failed to queue, not that the code was used.',
      },
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Sent', value: 'sent' },
        { label: 'Responded', value: 'responded' },
        { label: 'Error', value: 'error' },
      ],
    },
    {
      type: 'text',
      name: 'error_message',
      label: 'Error Message',
      admin: {
        condition: (data) => data?.status === 'error',
      },
    },
    {
      type: 'date',
      name: 'sent_at',
      label: 'Sent At',
      admin: {
        date: {
          pickerAppearance: 'dayAndTime',
        },
      },
    },
    {
      type: 'date',
      name: 'responded_at',
      label: 'Responded At',
      admin: {
        date: {
          pickerAppearance: 'dayAndTime',
        },
      },
    },
    {
      type: 'relationship',
      name: 'department',
      label: 'Department',
      relationTo: 'departments',
      required: false,
      filterOptions: filterByOperator,
      admin: {
        position: 'sidebar',
      },
    },
    {
      // "Resend Email" button in the list (per row) and the edit sidebar. Sends the email right
      // away with the row's existing code; hidden once the code has been used ('responded').
      type: 'ui',
      name: 'resend',
      label: 'Resend',
      admin: {
        position: 'sidebar',
        components: {
          Cell: './collections/survey-invitations/components/resend-button/index.tsx#ResendButtonCell',
          Field: './collections/survey-invitations/components/resend-button/index.tsx#ResendButtonField',
        },
      },
    },
    {
      type: 'relationship',
      name: 'operator',
      label: 'Operator',
      relationTo: 'operators',
      required: true,
    },
    {
      type: 'text',
      name: 'operator_slug',
      label: 'Operator Slug',
      admin: {
        readOnly: true,
        position: 'sidebar',
      },
    },
    CreatedByField,
    UpdatedByField,
  ],
  // Compound uniqueness: the same code may exist under different forms, so it must never be
  // a bare `unique: true` on `code` — only the (form, code) pair is unique.
  indexes: [{ fields: ['form', 'code'], unique: true }],
  // Access is scoped per survey form via the `survey-send-invitation-<form.slug>` grant — see
  // `./access.ts`. No dedicated `survey-invitations` grant, no operator scoping.
  access: {
    admin: surveyInvitationsAdminAccess,
    read: surveyInvitationsAccess('read'),
    create: surveyInvitationsCreateAccess,
    update: surveyInvitationsAccess('update'),
    delete: surveyInvitationsAccess('delete'),
  },
  hooks: {
    beforeValidate: [setOperatorSlugCollection('operator_slug')],
    beforeChange: [setUserCreatedOrUpdatedByCollection],
    afterChange: [auditLogAfterChange(SLUG)],
    afterDelete: [auditLogAfterDelete(SLUG)],
  },
}

export default SurveyInvitations
